<?php

/*
|--------------------------------------------------------------------------
| French defaults for Laravel's built-in validation rules
|--------------------------------------------------------------------------
|
| Registered unnamespaced by SharedServiceProvider, so the validator finds
| them as `validation.<rule>`. A form request's own messages() still win.
|
| Messages never use :attribute: errors render under their own field, and
| phrasing without it means no technical field path can leak. File sizes
| (:min, :max, :size, :value on files) are in kilobytes, hence « Ko ».
|
*/

return [

    'accepted' => 'Ce champ doit être accepté.',
    'accepted_if' => 'Ce champ doit être accepté quand :other vaut :value.',
    'active_url' => 'Cette valeur doit être une URL valide.',
    'after' => 'La date doit être postérieure au :date.',
    'after_or_equal' => 'La date doit être postérieure ou égale au :date.',
    'alpha' => 'Ce champ ne doit contenir que des lettres.',
    'alpha_dash' => 'Ce champ ne doit contenir que des lettres, des chiffres, des tirets et des tirets bas.',
    'alpha_num' => 'Ce champ ne doit contenir que des lettres et des chiffres.',
    'any_of' => 'Cette valeur est invalide.',
    'array' => 'Ce champ doit être une liste.',
    'array_keys' => 'Ce champ ne doit contenir que les clés suivantes : :values.',
    'ascii' => 'Ce champ ne doit contenir que des caractères alphanumériques et des symboles sur un octet.',
    'base64' => 'Cette valeur doit être une chaîne Base64 valide.',
    'before' => 'La date doit être antérieure au :date.',
    'before_or_equal' => 'La date doit être antérieure ou égale au :date.',
    'between' => [
        'array' => 'Ce champ doit contenir entre :min et :max éléments.',
        'file' => 'Le fichier doit peser entre :min et :max Ko.',
        'numeric' => 'La valeur doit être comprise entre :min et :max.',
        'string' => 'Le texte doit contenir entre :min et :max caractères.',
    ],
    'boolean' => 'Ce champ doit être vrai ou faux.',
    'can' => 'Ce champ contient une valeur non autorisée.',
    'confirmed' => 'La confirmation ne correspond pas.',
    'contains' => 'Il manque une valeur obligatoire dans ce champ.',
    'current_password' => 'Le mot de passe est incorrect.',
    'date' => 'Cette valeur doit être une date valide.',
    'date_equals' => 'La date doit être égale au :date.',
    'date_format' => 'Cette valeur doit respecter le format :format.',
    'decimal' => 'Ce nombre doit avoir :decimal décimales.',
    'declined' => 'Ce champ doit être refusé.',
    'declined_if' => 'Ce champ doit être refusé quand :other vaut :value.',
    'different' => 'Cette valeur doit être différente de :other.',
    'digits' => 'Ce nombre doit contenir :digits chiffres.',
    'digits_between' => 'Ce nombre doit contenir entre :min et :max chiffres.',
    'dimensions' => 'Les dimensions de l\'image ne sont pas valides.',
    'distinct' => 'Cette valeur est en double.',
    'doesnt_contain' => 'Ce champ ne doit contenir aucune des valeurs suivantes : :values.',
    'doesnt_end_with' => 'Cette valeur ne doit pas se terminer par l\'une des valeurs suivantes : :values.',
    'doesnt_start_with' => 'Cette valeur ne doit pas commencer par l\'une des valeurs suivantes : :values.',
    'email' => 'Cette valeur doit être une adresse e-mail valide.',
    'encoding' => 'Ce champ doit être encodé en :encoding.',
    'ends_with' => 'Cette valeur doit se terminer par l\'une des valeurs suivantes : :values.',
    'enum' => 'La valeur sélectionnée est invalide.',
    'exists' => 'La valeur sélectionnée est invalide.',
    'extensions' => 'Le fichier doit avoir l\'une des extensions suivantes : :values.',
    'file' => 'Ce champ doit être un fichier.',
    'filled' => 'Ce champ doit avoir une valeur.',
    'gt' => [
        'array' => 'Ce champ doit contenir plus de :value éléments.',
        'file' => 'Le fichier doit peser plus de :value Ko.',
        'numeric' => 'La valeur doit être supérieure à :value.',
        'string' => 'Le texte doit contenir plus de :value caractères.',
    ],
    'gte' => [
        'array' => 'Ce champ doit contenir au moins :value éléments.',
        'file' => 'Le fichier doit peser au moins :value Ko.',
        'numeric' => 'La valeur doit être supérieure ou égale à :value.',
        'string' => 'Le texte doit contenir au moins :value caractères.',
    ],
    'hex_color' => 'Cette valeur doit être une couleur hexadécimale valide.',
    'image' => 'Le fichier doit être une image.',
    'in' => 'La valeur sélectionnée est invalide.',
    'in_array' => 'Cette valeur doit exister dans :other.',
    'in_array_keys' => 'Ce champ doit contenir au moins l\'une des clés suivantes : :values.',
    'integer' => 'Cette valeur doit être un nombre entier.',
    'ip' => 'Cette valeur doit être une adresse IP valide.',
    'ipv4' => 'Cette valeur doit être une adresse IPv4 valide.',
    'ipv6' => 'Cette valeur doit être une adresse IPv6 valide.',
    'json' => 'Cette valeur doit être une chaîne JSON valide.',
    'list' => 'Ce champ doit être une liste.',
    'lowercase' => 'Ce champ doit être en minuscules.',
    'lt' => [
        'array' => 'Ce champ doit contenir moins de :value éléments.',
        'file' => 'Le fichier doit peser moins de :value Ko.',
        'numeric' => 'La valeur doit être inférieure à :value.',
        'string' => 'Le texte doit contenir moins de :value caractères.',
    ],
    'lte' => [
        'array' => 'Ce champ ne doit pas contenir plus de :value éléments.',
        'file' => 'Le fichier ne doit pas dépasser :value Ko.',
        'numeric' => 'La valeur doit être inférieure ou égale à :value.',
        'string' => 'Le texte ne doit pas dépasser :value caractères.',
    ],
    'mac_address' => 'Cette valeur doit être une adresse MAC valide.',
    'max' => [
        'array' => 'Ce champ ne doit pas contenir plus de :max éléments.',
        'file' => 'Le fichier ne doit pas dépasser :max Ko.',
        'numeric' => 'La valeur ne doit pas dépasser :max.',
        'string' => 'Le texte ne doit pas dépasser :max caractères.',
    ],
    'max_digits' => 'Ce nombre ne doit pas contenir plus de :max chiffres.',
    'maxstripped' => 'Ce champ ne doit pas dépasser :max caractères.',
    'mimes' => 'Le fichier doit être de type : :values.',
    'mimetypes' => 'Le fichier doit être de type : :values.',
    'min' => [
        'array' => 'Ce champ doit contenir au moins :min éléments.',
        'file' => 'Le fichier doit peser au moins :min Ko.',
        'numeric' => 'La valeur doit être au moins :min.',
        'string' => 'Le texte doit contenir au moins :min caractères.',
    ],
    'min_digits' => 'Ce nombre doit contenir au moins :min chiffres.',
    'minstripped' => 'Ce champ doit contenir au moins :min caractères.',
    'missing' => 'Ce champ doit être absent.',
    'missing_if' => 'Ce champ doit être absent quand :other vaut :value.',
    'missing_unless' => 'Ce champ doit être absent sauf si :other vaut :value.',
    'missing_with' => 'Ce champ doit être absent quand :values est présent.',
    'missing_with_all' => 'Ce champ doit être absent quand :values sont présents.',
    'multiple_of' => 'La valeur doit être un multiple de :value.',
    'not_in' => 'La valeur sélectionnée est invalide.',
    'not_regex' => 'Le format de cette valeur est invalide.',
    'numeric' => 'Cette valeur doit être un nombre.',
    'password' => [
        'letters' => 'Le mot de passe doit contenir au moins une lettre.',
        'mixed' => 'Le mot de passe doit contenir au moins une majuscule et une minuscule.',
        'numbers' => 'Le mot de passe doit contenir au moins un chiffre.',
        'symbols' => 'Le mot de passe doit contenir au moins un symbole.',
        'uncompromised' => 'Ce mot de passe est apparu dans une fuite de données. Veuillez en choisir un autre.',
    ],
    'present' => 'Ce champ doit être présent.',
    'present_if' => 'Ce champ doit être présent quand :other vaut :value.',
    'present_unless' => 'Ce champ doit être présent sauf si :other vaut :value.',
    'present_with' => 'Ce champ doit être présent quand :values est présent.',
    'present_with_all' => 'Ce champ doit être présent quand :values sont présents.',
    'prohibited' => 'Ce champ est interdit.',
    'prohibited_if' => 'Ce champ est interdit quand :other vaut :value.',
    'prohibited_if_accepted' => 'Ce champ est interdit quand :other est accepté.',
    'prohibited_if_declined' => 'Ce champ est interdit quand :other est refusé.',
    'prohibited_unless' => 'Ce champ est interdit sauf si :other fait partie de : :values.',
    'prohibits' => 'Ce champ interdit la présence de :other.',
    'regex' => 'Le format de cette valeur est invalide.',
    'required' => 'Ce champ est obligatoire.',
    'required_array_keys' => 'Ce champ doit contenir des entrées pour : :values.',
    'required_if' => 'Ce champ est obligatoire quand :other vaut :value.',
    'required_if_accepted' => 'Ce champ est obligatoire quand :other est accepté.',
    'required_if_declined' => 'Ce champ est obligatoire quand :other est refusé.',
    'required_trimmed' => 'Ce champ est obligatoire.',
    'required_unless' => 'Ce champ est obligatoire sauf si :other fait partie de : :values.',
    'required_with' => 'Ce champ est obligatoire quand :values est présent.',
    'required_with_all' => 'Ce champ est obligatoire quand :values sont présents.',
    'required_without' => 'Ce champ est obligatoire quand :values est absent.',
    'required_without_all' => 'Ce champ est obligatoire quand aucun de :values n\'est présent.',
    'same' => 'Cette valeur doit correspondre à :other.',
    'size' => [
        'array' => 'Ce champ doit contenir :size éléments.',
        'file' => 'Le fichier doit peser :size Ko.',
        'numeric' => 'La valeur doit être :size.',
        'string' => 'Le texte doit contenir :size caractères.',
    ],
    'starts_with' => 'Cette valeur doit commencer par l\'une des valeurs suivantes : :values.',
    'string' => 'Ce champ doit être du texte.',
    'timezone' => 'Cette valeur doit être un fuseau horaire valide.',
    'unique' => 'Cette valeur est déjà utilisée.',
    'uploaded' => 'L\'image ne vérifie pas les critères de taille et de format.',
    'uppercase' => 'Ce champ doit être en majuscules.',
    'url' => 'Cette valeur doit être une URL valide.',
    'ulid' => 'Cette valeur doit être un ULID valide.',
    'uuid' => 'Cette valeur doit être un UUID valide.',

    'custom' => [],

    'attributes' => [],

];
