blank_issues_enabled: false
contact_links:
  - name: Questions générales / Discussions
    url: https://github.com/fhemery/esperluettes/discussions
    about: Pour les questions d'usage ou les idées non finalisées, utilisez Discussions.
