<?php

namespace App\Domains\Announcement\Database\Factories;

use App\Domains\Announcement\Models\Announcement;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends Factory<Announcement>
 */
class AnnouncementFactory extends Factory
{
    protected $model = Announcement::class;

    public function definition(): array
    {
        $title = 'Announcement ' . uniqid();
        return [
            'title' => $title,
            'slug' => Str::slug($title),
            // slug generated by HasSlug
            'summary' => 'Summary for ' . $title,
            'content' => '<p>Content for ' . e($title) . '</p>',
            'header_image_path' => null,
            'is_pinned' => false,
            'display_order' => null,
            'status' => 'draft',
            'meta_description' => 'Meta description for ' . $title,
            'published_at' => null,
            'created_by' => 1,
        ];
    }

    public function published(): self
    {
        return $this->state(fn () => [
            'status' => 'published',
            'published_at' => \Illuminate\Support\Carbon::now(),
        ]);
    }

    public function pinned(?int $order = null): self
    {
        return $this->state(fn () => [
            'is_pinned' => true,
            'display_order' => $order,
        ]);
    }
}
